"""The landscape must agree with fusion, because it *is* fusion.

The failure this feature could produce is a confident, attractive picture of decision
boundaries that no longer match the code - so the landscape is generated by calling
`fuse_modulation` itself, and these tests pin that equivalence rather than re-deriving
the thresholds a third time.

The boundary tests deliberately probe either side of the two literal constants the
fusion module exports, so that moving a threshold in production breaks a test here
instead of silently producing a wrong diagram.
"""

import numpy as np
import pytest

from radiofry.fusion.confidence_fusion import (
    DIGITAL_FAMILY_MIN_CONFIDENCE,
    fuse_modulation,
)
from radiofry.fusion.decision_landscape import (
    ACCEPTED,
    ACCEPTED_REVIEW,
    ANALOG_RECOVERY,
    ANALOG_SUBTYPE,
    GUARD_BLOCK,
    GUARD_REROUTE,
    OUTCOMES,
    REJECTED,
    CapturePosition,
    LandscapeScenario,
    classify_outcome,
    describe_capture,
    evaluate_landscape,
    scenario_from_report,
    scenario_variants,
    threshold_lines,
)

AGREE = LandscapeScenario(ml_label="QPSK", classical_family="PSK-like",
                          ranked_alternatives=(("8PSK", 0.30), ("QAM64", 0.05)))
DISAGREE = LandscapeScenario(ml_label="QPSK", classical_family="FSK-like",
                             ranked_alternatives=(("8PSK", 0.30),))
GUARD_WEAK = LandscapeScenario(ml_label="WBFM", classical_family="FSK-like",
                               ranked_alternatives=(("GFSK", 0.30),))
GUARD_STRONG = LandscapeScenario(ml_label="WBFM", classical_family="FSK-like",
                                 ranked_alternatives=(("GFSK", 0.55),))
SUBTYPE = LandscapeScenario(ml_label="QPSK", classical_family="analog-like",
                            classical_evidence={"envelope_flatness": 0.55,
                                                "amplitude_cv": 0.20})
RECOVERY = LandscapeScenario(ml_label="QPSK", classical_family="analog-like",
                             ranked_alternatives=(("WBFM", 0.30),))


def _at(scenario: LandscapeScenario, cnn: float, classical: float):
    """The real fusion call the landscape makes for one point."""
    return fuse_modulation(
        scenario.ml_label, cnn, scenario.classical_family,
        threshold=scenario.threshold,
        alternatives=tuple(name for name, _ in scenario.ranked_alternatives),
        ranked_alternatives=scenario.ranked_alternatives,
        classical_evidence=scenario.classical_evidence,
        classical_confidence=classical)


# --- the landscape agrees with the fusion implementation --------------------------------


@pytest.mark.parametrize("scenario", [AGREE, DISAGREE, GUARD_WEAK, GUARD_STRONG,
                                      SUBTYPE, RECOVERY])
def test_every_cell_matches_a_direct_call_to_fuse_modulation(scenario) -> None:
    """The equivalence the whole feature rests on, checked cell by cell."""
    grid = evaluate_landscape(scenario, resolution=11)

    for row, classical in enumerate(grid.classical_axis):
        for column, cnn in enumerate(grid.cnn_axis):
            expected = _at(scenario, float(cnn), float(classical))
            assert grid.labels[row, column] == expected.label
            assert grid.trust[row, column] == pytest.approx(expected.trust_score)
            assert bool(grid.review[row, column]) == expected.review_recommended
            assert grid.outcomes[row, column] == classify_outcome(expected, scenario)


def test_the_grid_has_consistent_shapes_and_axes() -> None:
    grid = evaluate_landscape(AGREE, resolution=25)

    assert grid.cnn_axis.shape == (25,)
    assert grid.classical_axis.shape == (25,)
    assert grid.outcomes.shape == (25, 25)
    assert grid.labels.shape == grid.outcomes.shape
    assert grid.trust.shape == grid.outcomes.shape
    assert grid.cnn_axis[0] == 0.0 and grid.cnn_axis[-1] == 1.0
    assert np.all(np.diff(grid.cnn_axis) > 0)


def test_every_reported_outcome_key_is_documented() -> None:
    for scenario in (AGREE, DISAGREE, GUARD_WEAK, GUARD_STRONG, SUBTYPE, RECOVERY):
        for key in evaluate_landscape(scenario, resolution=9).present_outcomes:
            assert key in OUTCOMES
            assert OUTCOMES[key]["label"] and OUTCOMES[key]["detail"]


# --- each regime is reached, and only where the code says ---------------------------------


def test_a_confident_agreeing_digital_prediction_is_accepted() -> None:
    grid = evaluate_landscape(AGREE, resolution=41)

    assert grid.outcome_at(0.95, 0.9) == ACCEPTED
    assert grid.outcome_at(0.05, 0.9) == REJECTED


def test_family_disagreement_accepts_but_flags_review() -> None:
    grid = evaluate_landscape(DISAGREE, resolution=41)

    assert grid.outcome_at(0.95, 0.9) == ACCEPTED_REVIEW
    result = _at(DISAGREE, 0.95, 0.9)
    assert result.review_recommended is True
    assert result.trust_score == pytest.approx(0.95 * 0.5), "disagreement halves trust"


def test_the_analog_subtype_gate_takes_the_whole_plane_when_evidence_is_present() -> None:
    """Entry 032: once the classical detector says analog, the CNN does not vote."""
    grid = evaluate_landscape(SUBTYPE, resolution=21)

    assert set(np.unique(grid.outcomes).tolist()) == {ANALOG_SUBTYPE}
    assert grid.labels[0, 0] == "WBFM", "flatness 0.55 > 0.40 selects WBFM"
    assert grid.warnings, "a plane with one branch must say so"


def test_the_analog_subtype_rule_follows_the_envelope_thresholds() -> None:
    flat = LandscapeScenario(ml_label="QPSK", classical_family="analog-like",
                             classical_evidence={"envelope_flatness": 0.55,
                                                 "amplitude_cv": 0.20})
    ssb = LandscapeScenario(ml_label="QPSK", classical_family="analog-like",
                            classical_evidence={"envelope_flatness": 0.20,
                                                "amplitude_cv": 0.45})
    dsb = LandscapeScenario(ml_label="QPSK", classical_family="analog-like",
                            classical_evidence={"envelope_flatness": 0.20,
                                                "amplitude_cv": 0.20})

    assert evaluate_landscape(flat, resolution=5).labels[0, 0] == "WBFM"
    assert evaluate_landscape(ssb, resolution=5).labels[0, 0] == "AM-SSB"
    assert evaluate_landscape(dsb, resolution=5).labels[0, 0] == "AM-DSB"


def test_analog_recovery_only_applies_below_the_acceptance_threshold() -> None:
    """Entry 026: a rejected digital top-1 can be recovered as analog, not an accepted one."""
    grid = evaluate_landscape(RECOVERY, resolution=41)

    assert grid.outcome_at(0.10, 0.9) == ANALOG_RECOVERY
    assert grid.outcome_at(0.90, 0.9) == ACCEPTED_REVIEW


def test_the_digital_family_guard_blocks_when_no_alternative_clears_the_threshold() -> None:
    grid = evaluate_landscape(GUARD_WEAK, resolution=41)

    assert grid.outcome_at(0.90, 0.90) == GUARD_BLOCK
    assert grid.labels[-1, -1] == "Unclassified"


def test_the_digital_family_guard_reroutes_when_an_alternative_clears_it() -> None:
    grid = evaluate_landscape(GUARD_STRONG, resolution=41)

    assert grid.outcome_at(0.90, 0.90) == GUARD_REROUTE
    assert grid.labels[-1, -1] == "GFSK"


# --- boundaries sit on the exported constants ------------------------------------------------


def test_the_acceptance_boundary_is_the_threshold_itself() -> None:
    """Just below rejects, exactly at accepts: `rejected = probability < threshold`."""
    assert classify_outcome(_at(AGREE, 0.399, 0.9), AGREE) == REJECTED
    assert classify_outcome(_at(AGREE, 0.400, 0.9), AGREE) == ACCEPTED
    assert classify_outcome(_at(AGREE, 0.401, 0.9), AGREE) == ACCEPTED


def test_a_custom_threshold_moves_the_boundary_and_the_annotation() -> None:
    strict = LandscapeScenario(ml_label="QPSK", classical_family="PSK-like",
                               threshold=0.8)

    grid = evaluate_landscape(strict, resolution=41)

    assert grid.outcome_at(0.5, 0.9) == REJECTED
    assert grid.outcome_at(0.9, 0.9) == ACCEPTED
    assert threshold_lines(strict)[0]["value"] == pytest.approx(0.8)


def test_the_guard_boundary_is_the_digital_family_sufficiency_floor() -> None:
    """Either side of DIGITAL_FAMILY_MIN_CONFIDENCE, read from the fusion module."""
    below = DIGITAL_FAMILY_MIN_CONFIDENCE - 0.001
    at = DIGITAL_FAMILY_MIN_CONFIDENCE

    assert classify_outcome(_at(GUARD_WEAK, 0.9, below), GUARD_WEAK) != GUARD_BLOCK
    assert classify_outcome(_at(GUARD_WEAK, 0.9, at), GUARD_WEAK) == GUARD_BLOCK


def test_threshold_lines_only_claim_boundaries_that_exist_in_context() -> None:
    plain = threshold_lines(AGREE)
    guarded = threshold_lines(GUARD_WEAK)

    assert [line["axis"] for line in plain] == ["cnn"]
    assert {line["axis"] for line in guarded} == {"cnn", "classical"}
    assert any(line["value"] == DIGITAL_FAMILY_MIN_CONFIDENCE for line in guarded)


# --- reading a real report --------------------------------------------------------------------


def _report(cnn_label="QPSK", cnn_confidence=0.9, family="PSK-like",
            classical_confidence=0.8, top_k=None, evidence=None, fusion=None,
            snr_db=12.0):
    return {"stages": {
        "cnn_modulation": {"label": cnn_label, "confidence": cnn_confidence,
                           "top_k": top_k or [[cnn_label, cnn_confidence],
                                              ["8PSK", 0.05]],
                           "available": True},
        "classical_modulation": {"family": family, "confidence": classical_confidence,
                                 "evidence": evidence},
        "parameters": {"snr_db": snr_db},
        "fusion": fusion if fusion is not None else {
            "label": cnn_label, "trust_score": 0.99, "review_recommended": False,
            "analog_route": "", "digital_family_block": False},
    }}


def test_a_recorded_analysis_rebuilds_the_context_it_presented_to_fusion() -> None:
    scenario = scenario_from_report(_report(top_k=[["QPSK", 0.9], ["8PSK", 0.07],
                                                   ["QAM64", 0.03]]))

    assert scenario is not None
    assert scenario.ml_label == "QPSK"
    assert scenario.classical_family == "PSK-like"
    assert scenario.ranked_alternatives == (("8PSK", 0.07), ("QAM64", 0.03)), (
        "top_k[1:] is what the pipeline passes as alternatives")


def test_a_capture_position_reproduces_the_recorded_decision() -> None:
    position = describe_capture(_report())

    assert position.plottable
    assert position.cnn_confidence == pytest.approx(0.9)
    assert position.classical_confidence == pytest.approx(0.8)
    assert position.snr_db == pytest.approx(12.0)
    assert position.reproduced is True
    assert position.outcome == ACCEPTED
    assert position.notes == ()


def test_a_position_that_does_not_reproduce_is_flagged_rather_than_drawn_anyway() -> None:
    """If replaying the inputs disagrees with the record, the point is not trustworthy."""
    mismatched = _report(fusion={"label": "8PSK", "trust_score": 0.5,
                                 "review_recommended": False, "analog_route": "",
                                 "digital_family_block": False})

    position = describe_capture(mismatched)

    assert position.reproduced is False
    assert position.notes and "may not correspond" in position.notes[0]


def test_triggered_guards_are_named_from_the_recorded_result() -> None:
    blocked = describe_capture(_report(fusion={
        "label": "Unclassified", "trust_score": 0.2, "review_recommended": True,
        "analog_route": "", "digital_family_block": True}))
    subtype = describe_capture(_report(fusion={
        "label": "WBFM", "trust_score": 0.9, "review_recommended": True,
        "analog_route": "classical_subtype", "digital_family_block": False}))
    recovered = describe_capture(_report(fusion={
        "label": "WBFM", "trust_score": 0.4, "review_recommended": True,
        "analog_route": "cnn_alternative", "digital_family_block": False}))

    assert any("digital-family guard" in g for g in blocked.guards)
    assert any("analog subtype gate" in g for g in subtype.guards)
    assert any("analog recovery" in g for g in recovered.guards)


# --- missing and invalid inputs -----------------------------------------------------------------


def test_a_missing_report_yields_an_unplottable_position_not_an_error() -> None:
    for report in (None, {}, {"stages": {}}):
        position = describe_capture(report)
        assert isinstance(position, CapturePosition)
        assert not position.plottable


def test_an_unavailable_cnn_prediction_is_explained() -> None:
    report = {"stages": {
        "cnn_modulation": {"available": False, "label": None, "confidence": None,
                           "message": "checkpoint missing"},
        "classical_modulation": {"family": "PSK-like", "confidence": 0.8},
        "fusion": {"label": "Unclassified"}}}

    position = describe_capture(report)

    assert not position.plottable
    assert position.notes and "No CNN prediction" in position.notes[0]


def test_non_numeric_confidences_do_not_crash_the_extraction() -> None:
    report = _report(cnn_confidence="not a number", classical_confidence=None)

    position = describe_capture(report)

    assert position.cnn_confidence is None
    assert position.classical_confidence is None
    assert not position.plottable


def test_scenario_extraction_refuses_a_report_without_the_pieces() -> None:
    assert scenario_from_report({"stages": {"cnn_modulation": {"label": None}}}) is None
    assert scenario_from_report({"stages": {"classical_modulation": "broken",
                                            "cnn_modulation": {}}}) is None
    assert scenario_from_report(None) is None


def test_scenario_variants_reach_distinct_regimes() -> None:
    variants = scenario_variants(AGREE)

    outcomes = {name: set(evaluate_landscape(s, resolution=9).present_outcomes)
                for name, s in variants.items()}
    assert ANALOG_SUBTYPE in outcomes["Classical analog with envelope evidence"]
    assert GUARD_BLOCK in outcomes["CNN analog vs classical digital (guard)"] or \
        GUARD_REROUTE in outcomes["CNN analog vs classical digital (guard)"]
    assert outcomes["This capture"] != outcomes["Classical analog with envelope evidence"]
